import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./_components/Provider";
import { session } from 'next-auth'
import AuthProvider from "@/app/BackEnd/component/AuthProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider session={session}>
          <Provider>

            {children}

          </Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
